describe('template spec', () => {
  it('passes', () => {
    cy.visit('https://forhemer.github.io/React-Todo-List/')
    cy.get('[name="title"]').type("Первое дело")
    cy.get('[type="submit"]').click()
    cy.get('[name="title"]').type("Второе дело")
    cy.get('[type="submit"]').click()
    cy.get('[name="title"]').type("Третье дело")
    cy.get('[type="submit"]').click()
    cy.get('[class="TodoItem_item__iFWQW"]')
    cy.get('[type="checkbox"]')
      .first()
      .check()
    cy.get('[class="TodoItem_item__iFWQW"]')
      .get('li:first span')
      .should('have.css', 'text-decoration-line', 'line-through')
    cy.get('[type="button"]:first').click()
    cy.get('[class="TodoItem_item__iFWQW"]')
      .get('li:first span')
      .contains('Первое дело')
  })
})